#!/usr/bin/env bash

# This scripts invokes the actual php class and determines
# its actual path to invoke the right class
# This script is also the one which will be symlinked to bin

# see http://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SRC_DIR="$(dirname "$(readlink -f "$0")")"
args="$@"

php $SRC_DIR/MStruebing/EditorconfigChecker/EditorconfigChecker.php $args
