#!/usr/bin/env bash

# This scripts invokes the actual php class and determines
# its actual path to invoke the right class
# This script is also the one which will be symlinked to bin

# on osx//bsd there is no readlink :(
# so I have to use this like said here:
# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
function bsdCompatibleReadLink() {
	local TARGET_FILE="$1"

	cd `dirname $TARGET_FILE`
	TARGET_FILE=`basename $TARGET_FILE`

	# Iterate down a (possible) chain of symlinks
	while [ -L "$TARGET_FILE" ]
	do
	    TARGET_FILE=`readlink $TARGET_FILE`
	    cd `dirname $TARGET_FILE`
	    TARGET_FILE=`basename $TARGET_FILE`
	done

	# Compute the canonicalized name by finding the physical path
	# for the directory we're in and appending the target file.
	PHYS_DIR=`pwd -P`
	RESULT=$PHYS_DIR/$TARGET_FILE
	echo $RESULT
}

# see http://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SRC_DIR="$(dirname "$(bsdCompatibleReadLink "$0")")"
args="$@"

php $SRC_DIR/MStruebing/EditorconfigChecker/EditorconfigChecker.php $args
